echo "This file doesnt do anything, its just a guide"
echo "cryptsetup open /dev/LUKSPART cryptroot"
echo "mkfs.fat -F32 /dev/BOOTPART -n boot"
echo "mkfs.btrfs /dev/mapper/cryptroot -f -L root"
echo "mount /dev/disk-by-label/root /mnt"
echo "mkdir /mnt/boot"
echo "mount /dev/disk-by-label/boot /mnt/boot"
echo "pacstrap -K /mnt base linux linux-firmware vim man-db"
echo "genfstab -U /mnt >> /mnt/etc/fstab"
