"$schema" = 'https://starship.rs/config-schema.json'

# order: blue green yellow orange dark
format = """
[](blue_bg)\
$os\
$username\
[](bg:green_bg fg:blue_bg)\
$directory\
[](fg:green_bg bg:yellow_bg)\
$git_branch\
$git_status\
[](fg:yellow_bg bg:orange_bg)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:orange_bg bg:dark_bg)\
$docker_context\
$conda\
[](fg:dark_bg)\
$line_break$character"""

palette = 'idk'

[palettes.idk]
dark_bg = '#112233'
white_fg = '#ccffcc'
green_fg = '#22ff22'
green_bg = '#225522'
red_bg = '#552222'
red_fg = '#ff2222'
blue_bg = '#222255'
blue_fg = '#2222ff'
yellow_fg = '#ffff22'
yellow_bg = '#555522'
orange_fg = '#ffff22'
orange_bg = '#663322'

[os]
disabled = false
style = "bg:blue_bg fg:white_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:blue_bg fg:white_fg"
style_root = "bg:blue_bg fg:white_fg"
format = '[ $user ]($style)'

[directory]
style = "fg:white_fg bg:green_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow_bg"
format = '[[ $symbol $branch ](fg:white_fg bg:yellow_bg)]($style)'

[git_status]
style = "bg:yellow_bg"
format = '[[($all_status$ahead_behind )](fg:white_fg bg:yellow_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[c]
symbol = " "
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[rust]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[golang]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[php]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[java]
symbol = " "
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[kotlin]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[haskell]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ](fg:white_fg bg:orange_bg)]($style)'

[python]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $version) ${virtualenv} ](fg:white_fg bg:orange_bg)]($style)'
#format = "via [(${virtualenv})]($style) "

[docker_context]
symbol = ""
style = "bg:orange_bg"
format = '[[ $symbol( $context) ](fg:#83a598 bg:orange_bg)]($style)'

[conda]
style = "bg:orange_bg"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:orange_bg)]($style)'

#[time]
#disabled = false
#time_format = "%R"
#style = "bg:orange_bg"
#format = '[[  $time ](fg:white_fg bg:orange_bg)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[->](bold fg:green_fg)'
error_symbol = '[->](bold fg:red_fg)'
vimcmd_symbol = '[<-](bold fg:yellow_fg)'
vimcmd_replace_one_symbol = '[<-](bold fg:blue_fg)'
vimcmd_replace_symbol = '[<-](bold fg:blue_fg)'
vimcmd_visual_symbol = '[<-](bold fg:yellow_fg)'
